version: "3.8"
services:
  db:
    image: postgres
    container_name: nest-js-db
    tty: true
    environment:
      - POSTGRES_DB=nest-js
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - nest-js-pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - portal-network
networks:
  portal-network:
    driver: bridge
    external: true
volumes:
  nest-js-pgdata:
    external: true
